sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start test...!"
  - docker build -t bpeak/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true bpeak/docker-test npm run test

after_success:
  - echo "test success...!"